{{ $password := (pluck .Values.global.env .Values.envs.MYSQL_PASSWORD | first | default .Values.envs.MYSQL_PASSWORD._default) }}
---
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ .Chart.Name }}
data:
  MYSQL_PASSWORD:  {{ $password | b64enc | quote }}